supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: EcommerceBundle:Panier:supprimer}

ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: EcommerceBundle:Panier:ajouter}

panier:
    path:     /
    defaults: { _controller: EcommerceBundle:Panier:panier}

validation:
    path:     /validation
    defaults: { _controller: EcommerceBundle:Panier:validation }